export type Locale = "ru" | "en";

export const content = {
  ru: {
    nav: { about: "О проекте", locations: "Где установить", benefits: "Преимущества", partners: "Для партнёров", contact: "Контакты", partnerCta: "Стать партнёром" },
    hero: { title: "Женская гигиена доступна в любой момент", body: "Современные вендинговые аппараты со средствами женской гигиены в аэропортах, университетах, торговых и бизнес-центрах Москвы.", badge: "Средства гигиены рядом, когда это важно", feedback: "Оставить отзыв" },
    facts: ["Доступность 24/7", "Карта, СБП и приложение", "Проверенный ассортимент", "Регулярное обслуживание"],
    about: { title: "Забота, которая нужна здесь и сейчас", text: "Каждая женщина хотя бы раз оказывалась в ситуации, когда средство гигиены нужно прямо сейчас, а рядом нет ни аптеки, ни магазина. Особенно часто это происходит в аэропортах, университетах и других общественных пространствах. Поэтому EVA развивает сеть вендинговых аппаратов со средствами женской гигиены, чтобы нужные товары были рядом именно в тот момент, когда они необходимы.", phrase: "Комфорт начинается с доступности.", places: ["Аэропорты", "Университеты", "Общественные пространства", "Бизнес-центры и ТРЦ"] },
    products: {
      title: "Всё необходимое в одном аппарате",
      items: ["Прокладки", "Тампоны", "Ежедневные прокладки", "Влажные салфетки"],
      text: "Мы формируем ассортимент из товаров проверенных брендов и удобных форматов упаковки.",
      paymentLead: "Удобная безналичная оплата:",
      paymentMethods: ["Банковская карта", "СБП", "Мобильное приложение"],
      disclaimer: "Упоминание торговых марок носит информационный характер. Ассортимент может отличаться в зависимости от локации."
    },
    values: { title: "Не просто вендинг. Пространство заботы.", text: "Я работаю косметологом-эстетистом и ежедневно общаюсь с женщинами. Я вижу, насколько важно чувствовать комфорт, уверенность и заботу о себе. Но такая базовая потребность, как доступ к средствам гигиены, до сих пор не всегда решена в общественных местах. Этот проект не только о продажах. Он о комфортной городской среде, уважении к женщинам и возможности чувствовать себя спокойно в любой ситуации.", cards: ["Забота о женщинах", "Комфортная городская среда", "Нормализация темы женской гигиены"], quote: "Я хочу, чтобы каждая девушка чувствовала себя уверенно в любой ситуации.", author: "Ксения Галимуллина, основательница EVA" },
    locations: { title: "Там, где это особенно важно", items: ["Аэропорты Москвы", "Крупные ТРЦ", "Университеты и кампусы", "Бизнес-центры", "Коворкинги"], text: "Аппараты размещаются в женских туалетных зонах или рядом с ними, там, где покупка нужна быстро, удобно и деликатно.", status: "Сейчас ведём переговоры о возможном размещении аппаратов в аэропортах Внуково и Домодедово." },
    benefits: { title: "Удобно для посетительниц. Просто для площадки.", women: "Для женщин", venues: "Для площадки", womenItems: ["Средства гигиены доступны рядом", "Покупка в нужный момент", "Карта, СБП и мобильное приложение", "Удобный и деликатный формат покупки", "Проверенный ассортимент"], venueItems: ["Дополнительный сервис для посетительниц", "Современное решение для комфортной инфраструктуры", "Компактный формат размещения", "Регулярное обслуживание аппарата", "Возможность усилить заботу о клиентах, сотрудницах и студентках"] },
    partner: { title: "Хотите установить аппарат на своей площадке?", intro: "Оставьте контакты, мы расскажем о формате размещения, обслуживании и возможностях сотрудничества.", organization: "Наименование организации", venue: "Тип площадки", city: "Город", person: "Контактное лицо", phone: "Телефон", email: "Email", message: "Комментарий", consent: "Я согласен(а) с политикой конфиденциальности", submit: "Отправить заявку", success: "Спасибо! Мы получили вашу заявку и свяжемся с вами в ближайшее время.", privacy: "Мы не передаём контакты третьим лицам и используем их только для связи по вашей заявке." },
    contact: { title: "Есть вопрос, отзыв или предложение?", intro: "Если вы уже пользовались аппаратом, заметили техническую неполадку или хотите предложить новую локацию, напишите нам. Ваше мнение помогает делать сервис лучше.", request: "Тип обращения", location: "Локация аппарата или город", name: "Имя", response: "Email или телефон для ответа", message: "Сообщение", consent: "Я согласен(а) с политикой конфиденциальности", submit: "Отправить сообщение", success: "Спасибо за сообщение! Мы уже получили его и внимательно всё изучим." },
    footer: { slogan: "С заботой о себе", description: "Женская гигиена рядом, когда это важно.", rights: "© 2026 EVA. С заботой о себе.", privacy: "Политика конфиденциальности", write: "Написать нам", call: "Позвонить" },
    partnerPage: { title: "Забота о посетительницах: часть современной инфраструктуры", intro: "Аппараты EVA для аэропортов, ТРЦ, университетов, бизнес-центров и коворкингов Москвы.", suitable: "Для каких площадок подходит", value: "Ценность для площадки", how: "Как устроено сотрудничество", details: "Детали размещения и формат обслуживания обсуждаются индивидуально с каждой площадкой.", steps: ["Вы оставляете заявку.", "Мы обсуждаем формат и предполагаемое место размещения.", "Согласовываем условия.", "Организуем установку и обслуживание."] }
  },
  en: {
    nav: { about: "About", locations: "Locations", benefits: "Benefits", partners: "For partners", contact: "Contacts", partnerCta: "Become a partner" },
    hero: { title: "Feminine hygiene, available whenever you need it.", body: "Modern vending machines with feminine hygiene products for Moscow airports, universities, shopping centres and business centres.", badge: "Essential hygiene products, right when they matter", feedback: "Leave feedback" },
    facts: ["Available 24/7", "Card, SBP and app", "Thoughtful assortment", "Regular service"],
    about: { title: "Care that is needed here and now", text: "Most women have faced a moment when a hygiene product was needed immediately, yet no pharmacy or shop was nearby. It happens especially often in airports, universities and other public spaces. EVA is building a network of feminine hygiene vending machines so that essential products are there precisely when they are needed.", phrase: "Comfort begins with accessibility.", places: ["Airports", "Universities", "Public spaces", "Business and shopping centres"] },
    products: {
      title: "Everything essential in one machine",
      items: ["Sanitary pads", "Tampons", "Panty liners", "Wet wipes"],
      text: "We curate products from trusted brands in convenient pack formats.",
      paymentLead: "Easy cashless payment:",
      paymentMethods: ["Bank card", "SBP", "Mobile app"],
      disclaimer: "Trademark references are provided for information only. Assortment may differ by location."
    },
    values: { title: "More than vending. A space for care.", text: "As an aesthetician, I speak with women every day. I see how much comfort, confidence and care matter. Yet access to hygiene products is still not always solved in public places. This project is not only about sales. It is about a comfortable urban environment, respect for women and peace of mind in any situation.", cards: ["Care for women", "A comfortable urban environment", "Making feminine hygiene a normal topic"], quote: "I want every woman to feel confident in any situation.", author: "Kseniya Galimullina, EVA founder" },
    locations: { title: "Where it matters most", items: ["Moscow airports", "Major shopping centres", "Universities and campuses", "Business centres", "Coworking spaces"], text: "Machines are placed in or near women’s restroom areas, where a purchase needs to be quick, convenient and discreet.", status: "We are currently discussing potential placement at Vnukovo and Domodedovo airports." },
    benefits: { title: "Easy for visitors. Simple for venues.", women: "For women", venues: "For venues", womenItems: ["Hygiene products close by", "Purchase at the moment of need", "Card, SBP and mobile app", "A convenient and discreet format", "Thoughtful assortment"], venueItems: ["An added service for visitors", "A modern solution for comfortable infrastructure", "Compact placement", "Regular machine servicing", "A way to show care for clients, employees and students"] },
    partner: { title: "Would you like a machine at your venue?", intro: "Leave your details and we will explain placement, service and partnership options.", organization: "Organisation name", venue: "Venue type", city: "City", person: "Contact person", phone: "Phone", email: "Email", message: "Comment", consent: "I agree to the privacy policy", submit: "Send application", success: "Thank you. We received your application and will be in touch soon.", privacy: "We do not share contacts with third parties and use them only to respond to your application." },
    contact: { title: "A question, feedback or suggestion?", intro: "If you have used a machine, noticed a technical issue or want to suggest a location, write to us. Your feedback helps make the service better.", request: "Request type", location: "Machine location or city", name: "Name", response: "Email or phone for reply", message: "Message", consent: "I agree to the privacy policy", submit: "Send message", success: "Thank you for your message. We have received it and will review it carefully." },
    footer: { slogan: "Care for yourself", description: "Feminine hygiene, close by when it matters.", rights: "© 2026 EVA. Care for yourself.", privacy: "Privacy policy", write: "Write to us", call: "Call" },
    partnerPage: { title: "Care for visitors: part of modern infrastructure", intro: "EVA machines for Moscow airports, shopping centres, universities, business centres and coworking spaces.", suitable: "Suitable venues", value: "Value for the venue", how: "How partnership works", details: "Placement details and service arrangements are discussed individually with every venue.", steps: ["You leave an application.", "We discuss the format and a possible placement area.", "We agree on the terms.", "We arrange installation and servicing."] }
  }
} as const;

export type SiteCopy = (typeof content)[Locale];
