"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { customerSchema, partnerSchema, type CustomerInput, type PartnerInput } from "@/lib/validations";
import { useForm } from "react-hook-form";
import Link from "next/link";
import { useLanguage } from "./language-provider";

const venueValues = ["airport", "mall", "university", "business", "coworking", "other"];
const requestValues = ["feedback", "question", "support", "suggest_location", "other"];

function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}{error && <small role="alert">{error}</small>}</label>; }
function Consent({ id, label, error, register }: { id: string; label: string; error?: string; register: ReturnType<typeof useForm>["register"] }) { return <div><label className="consent"><input id={id} type="checkbox" {...register("privacyConsent")} /><span>{label} <Link href="/privacy">{label.includes("privacy") ? "privacy policy" : "политикой конфиденциальности"}</Link></span></label>{error && <small role="alert">{error}</small>}</div>; }

export function PartnerForm() {
  const { copy, locale } = useLanguage(); const t = copy.partner;
  const { register, handleSubmit, formState: { errors, isSubmitting, isSubmitSuccessful }, setError } = useForm<PartnerInput>({ resolver: zodResolver(partnerSchema), defaultValues: { city: locale === "ru" ? "Москва" : "Moscow" } });
  const submit = async (values: PartnerInput) => { const res = await fetch("/api/partner-inquiry", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); if (!res.ok) setError("root", { message: locale === "ru" ? "Не удалось отправить заявку. Попробуйте ещё раз или свяжитесь с нами по телефону." : "Could not send the application. Please try again or call us." }); };
  if (isSubmitSuccessful && !errors.root) return <p className="form-success" role="status">{t.success}</p>;
  return <form className="eva-form" onSubmit={handleSubmit(submit)} noValidate><input className="honeypot" tabIndex={-1} autoComplete="off" {...register("website")} /><Field label={t.organization} error={errors.organizationName?.message}><input {...register("organizationName")} /></Field><div className="form-row"><Field label={t.venue} error={errors.venueType?.message}><select {...register("venueType")}><option value="">{locale === "ru" ? "Выберите вариант" : "Select an option"}</option>{venueValues.map((value) => <option key={value} value={value}>{({ airport: locale === "ru" ? "Аэропорт" : "Airport", mall: locale === "ru" ? "ТРЦ" : "Shopping centre", university: locale === "ru" ? "Университет" : "University", business: locale === "ru" ? "Бизнес-центр" : "Business centre", coworking: locale === "ru" ? "Коворкинг" : "Coworking", other: locale === "ru" ? "Другое" : "Other" })[value]}</option>)}</select></Field><Field label={t.city} error={errors.city?.message}><input {...register("city")} /></Field></div><div className="form-row"><Field label={t.person} error={errors.contactName?.message}><input {...register("contactName")} /></Field><Field label={t.phone} error={errors.phone?.message}><input type="tel" {...register("phone")} /></Field></div><Field label={t.email} error={errors.email?.message}><input type="email" {...register("email")} /></Field><Field label={t.message} error={errors.message?.message}><textarea rows={3} {...register("message")} /></Field><Consent id="partner-consent" label={t.consent} error={errors.privacyConsent?.message} register={register as never} />{errors.root && <p className="form-error" role="alert">{errors.root.message}</p>}<button className="button primary" disabled={isSubmitting}>{isSubmitting ? "..." : t.submit}</button><p className="form-note">{t.privacy}</p></form>;
}

export function CustomerForm() {
  const { copy, locale } = useLanguage(); const t = copy.contact;
  const { register, handleSubmit, formState: { errors, isSubmitting, isSubmitSuccessful }, setError } = useForm<CustomerInput>({ resolver: zodResolver(customerSchema) });
  const submit = async (values: CustomerInput) => { const res = await fetch("/api/customer-message", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); if (!res.ok) setError("root", { message: locale === "ru" ? "Не удалось отправить сообщение. Попробуйте ещё раз или свяжитесь с нами по телефону." : "Could not send the message. Please try again or call us." }); };
  if (isSubmitSuccessful && !errors.root) return <p className="form-success" role="status">{t.success}</p>;
  return <form className="eva-form" onSubmit={handleSubmit(submit)} noValidate><input className="honeypot" tabIndex={-1} autoComplete="off" {...register("website")} /><Field label={t.request} error={errors.requestType?.message}><select {...register("requestType")}><option value="">{locale === "ru" ? "Выберите вариант" : "Select an option"}</option>{requestValues.map((value) => <option key={value} value={value}>{({ feedback: locale === "ru" ? "Отзыв" : "Feedback", question: locale === "ru" ? "Вопрос" : "Question", support: locale === "ru" ? "Техническая поддержка" : "Technical support", suggest_location: locale === "ru" ? "Предложить локацию" : "Suggest a location", other: locale === "ru" ? "Другое" : "Other" })[value]}</option>)}</select></Field><div className="form-row"><Field label={t.location} error={errors.location?.message}><input {...register("location")} /></Field><Field label={t.name} error={errors.name?.message}><input {...register("name")} /></Field></div><Field label={t.response} error={errors.contact?.message}><input {...register("contact")} /></Field><Field label={t.message} error={errors.message?.message}><textarea rows={3} {...register("message")} /></Field><Consent id="customer-consent" label={t.consent} error={errors.privacyConsent?.message} register={register as never} />{errors.root && <p className="form-error" role="alert">{errors.root.message}</p>}<button className="button primary" disabled={isSubmitting}>{isSubmitting ? "..." : t.submit}</button></form>;
}
