"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { AirplaneTilt, Buildings, CaretDown, ChatCircleText, Check, EnvelopeSimple, MapPin, Phone, ShoppingBag, Student, WhatsappLogo } from "@phosphor-icons/react";
import { site } from "@/config/site";
import { useLanguage } from "./language-provider";
import { Reveal } from "./reveal";
import { MachineIllustration } from "./machine-illustration";
import { CustomerForm, PartnerForm } from "./forms";

const icons = [AirplaneTilt, Student, MapPin, Buildings];
const productShapes = ["droplet", "arc", "oval", "grid"];

function LocaleToggle() { const { locale, setLocale } = useLanguage(); return <div className="locale-toggle" aria-label="Language"><button className={locale === "ru" ? "active" : ""} onClick={() => setLocale("ru")}>RU</button><span>|</span><button className={locale === "en" ? "active" : ""} onClick={() => setLocale("en")}>EN</button></div>; }

export function Header() {
  const { copy } = useLanguage(); const [open, setOpen] = useState(false);
  useEffect(() => { document.body.style.overflow = open ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [open]);
  const links = [["#about", copy.nav.about], ["#locations", copy.nav.locations], ["#benefits", copy.nav.benefits], ["/partners", copy.nav.partners], ["#contact", copy.nav.contact]] as const;
  return <header className="header"><Link className="brand" href="/"><b>EVA</b><span>с заботой о себе</span></Link><nav className={open ? "nav open" : "nav"} aria-label="Основная навигация">{links.map(([href, label]) => <Link key={href} href={href} onClick={() => setOpen(false)}>{label}</Link>)}<div className="mobile-locale"><LocaleToggle /></div><a className="button primary nav-cta" href="#partners" onClick={() => setOpen(false)}>{copy.nav.partnerCta}</a></nav><div className="header-actions"><LocaleToggle /><a className="button primary desktop-cta" href="#partners">{copy.nav.partnerCta}</a><button className="menu-button" aria-expanded={open} aria-label="Открыть меню" onClick={() => setOpen(!open)}><i /><i /></button></div></header>;
}

export function Hero() { const { copy } = useLanguage(); return <section className="hero"><div className="hero-copy"><Reveal><h1>{copy.hero.title}</h1><p>{copy.hero.body}</p><div className="hero-actions"><a className="button primary" href="#partners">{copy.nav.partnerCta}</a><a className="button secondary" href="#contact">{copy.hero.feedback}</a></div></Reveal></div><Reveal className="hero-art"><MachineIllustration /><span className="hero-badge">{copy.hero.badge}</span></Reveal></section>; }

export function Facts() { const { copy } = useLanguage(); return <section className="facts" aria-label="Ключевые факты"><p>Комфорт. Доступность. Забота о женщинах.</p><div>{copy.facts.map((fact, index) => <span key={fact}><b>0{index + 1}</b>{fact}</span>)}</div></section>; }

export function About() { const { copy } = useLanguage(); return <section id="about" className="section about"><Reveal><h2>{copy.about.title}</h2><p className="body-copy">{copy.about.text}</p></Reveal><div className="place-grid">{copy.about.places.map((place, i) => { const Icon = icons[i]; return <Reveal key={place}><article className="place-card"><Icon size={27} weight="regular" /><span>{place}</span></article></Reveal>; })}</div><p className="phrase">{copy.about.phrase}</p></section>; }

export function Products() { const { copy } = useLanguage(); return <section className="section products"><Reveal><h2>{copy.products.title}</h2></Reveal><div className="product-grid">{copy.products.items.map((item, i) => <Reveal key={item}><article className="product-card"><span className={`product-shape ${productShapes[i]}`} /><ShoppingBag size={25} /><h3>{item}</h3></article></Reveal>)}</div><Reveal><div className="product-notes"><p>{copy.products.text}</p><p>{copy.products.payment}</p><b>EVA · Always · Kotex</b><small>{copy.products.disclaimer}</small></div></Reveal></section>; }

export function Values() { const { copy } = useLanguage(); return <section className="values"><Reveal><div className="values-copy"><h2>{copy.values.title}</h2><p>{copy.values.text}</p><div className="value-cards">{copy.values.cards.map((card) => <span key={card}><Check size={20} />{card}</span>)}</div></div></Reveal><Reveal><aside className="quote-panel"><div className="quote-pattern" /><blockquote>«{copy.values.quote}»</blockquote><cite>{copy.values.author}</cite></aside></Reveal></section>; }

export function Locations() { const { copy } = useLanguage(); return <section id="locations" className="section locations"><Reveal><h2>{copy.locations.title}</h2></Reveal><div className="location-layout"><div className="location-list">{copy.locations.items.map((item) => <Reveal key={item}><span><MapPin size={22} weight="regular" />{item}</span></Reveal>)}</div><Reveal><div className="location-copy"><p>{copy.locations.text}</p><aside className="status"><AirplaneTilt size={30} /><p>{copy.locations.status}</p></aside></div></Reveal></div></section>; }

function ListColumn({ title, items, emphasis = false }: { title: string; items: readonly string[]; emphasis?: boolean }) { return <article className={emphasis ? "benefit-column emphasis" : "benefit-column"}><h3>{title}</h3><ul>{items.map((item) => <li key={item}><Check size={19} />{item}</li>)}</ul></article>; }
export function Benefits() { const { copy } = useLanguage(); return <section id="benefits" className="section benefits"><Reveal><h2>{copy.benefits.title}</h2></Reveal><div className="benefit-columns"><Reveal><ListColumn title={copy.benefits.women} items={copy.benefits.womenItems} /></Reveal><Reveal><ListColumn title={copy.benefits.venues} items={copy.benefits.venueItems} emphasis /></Reveal></div></section>; }

export function PartnerSection() { const { copy } = useLanguage(); return <section id="partners" className="section form-section"><Reveal><div><h2>{copy.partner.title}</h2><p>{copy.partner.intro}</p></div></Reveal><Reveal><PartnerForm /></Reveal></section>; }

function ContactLinks() { const { copy } = useLanguage(); return <div className="contact-links"><a href={site.whatsapp} target="_blank" rel="noreferrer"><WhatsappLogo size={23} />WhatsApp</a><a href={site.phoneHref}><Phone size={21} />{copy.footer.call}</a><a href={`mailto:${site.email}`}><EnvelopeSimple size={22} />Email</a></div>; }
export function ContactSection() { const { copy } = useLanguage(); return <section id="contact" className="section contact-section"><Reveal><div><h2>{copy.contact.title}</h2><p>{copy.contact.intro}</p><ContactLinks /></div></Reveal><Reveal><CustomerForm /></Reveal></section>; }

export function Footer() { const { copy } = useLanguage(); return <footer><div className="footer-top"><div><b>EVA / ЕВА</b><p>{copy.footer.slogan}</p><p>{copy.footer.description}</p></div><div><Link href="/partners">{copy.nav.partners}</Link><a href="#about">{copy.nav.about}</a><a href="#contact">{copy.nav.contact}</a><Link href="/privacy">{copy.footer.privacy}</Link></div><div><a href={`mailto:${site.email}`}>{site.email}</a><a href={site.phoneHref}>{site.phone}</a><a href={site.whatsapp}>WhatsApp</a></div></div><p className="footer-bottom">{copy.footer.rights}</p></footer>; }

export function FloatingContact() { const { copy } = useLanguage(); const [open, setOpen] = useState(false); const ref = useRef<HTMLDivElement>(null); useEffect(() => { const close = (event: MouseEvent) => { if (!ref.current?.contains(event.target as Node)) setOpen(false); }; const esc = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("mousedown", close); document.addEventListener("keydown", esc); return () => { document.removeEventListener("mousedown", close); document.removeEventListener("keydown", esc); }; }, []); return <div ref={ref} className="floating-contact"><div className={open ? "contact-popover visible" : "contact-popover"}><a href={site.whatsapp} target="_blank" rel="noreferrer">WhatsApp</a><a href={site.phoneHref}>{copy.footer.call}</a><a href={`mailto:${site.email}`}>Email</a></div><button className="button primary" aria-label={copy.footer.write} aria-expanded={open} onClick={() => setOpen(!open)}><ChatCircleText size={21} />{copy.footer.write}<CaretDown size={15} /></button></div>; }

export function HomePage() { return <><Header /><main><Hero /><Facts /><About /><Products /><Values /><Locations /><Benefits /><PartnerSection /><ContactSection /></main><Footer /><FloatingContact /></>; }

export function PartnerPage() { const { copy } = useLanguage(); const venues = copy.locations.items; const value = copy.benefits.venueItems; return <><Header /><main><section className="partner-hero"><Reveal><p className="kicker">EVA / B2B</p><h1>{copy.partnerPage.title}</h1><p>{copy.partnerPage.intro}</p><a className="button primary" href="#partner-form">{copy.nav.partnerCta}</a></Reveal></section><section className="section partner-info"><Reveal><h2>{copy.partnerPage.suitable}</h2><div className="pill-list">{venues.map((item) => <span key={item}>{item}</span>)}</div></Reveal><Reveal><h2>{copy.partnerPage.value}</h2><div className="value-cards">{value.map((item) => <span key={item}><Check size={20} />{item}</span>)}</div></Reveal><Reveal><h2>{copy.partnerPage.how}</h2><ol className="steps">{copy.partnerPage.steps.map((item, i) => <li key={item}><b>0{i + 1}</b>{item}</li>)}</ol><p>{copy.partnerPage.details}</p></Reveal></section><section id="partner-form" className="section form-section"><div><h2>{copy.partner.title}</h2><p>{copy.partner.intro}</p></div><PartnerForm /></section></main><Footer /><FloatingContact /></>; }

export function PrivacyPage() { const { locale } = useLanguage(); const ru = locale === "ru"; const blocks = ru ? [["Оператор", "Ксения Галимуллина. TODO: проверить с юристом статус оператора и реквизиты до публикации."], ["Какие данные собираем", "Данные из форм: имя, контакты, организация, тип обращения, город и текст сообщения."], ["Цели обработки", "Ответ на обращение, обсуждение сотрудничества и улучшение сервиса."], ["Согласие и защита", "Данные обрабатываются с согласия посетителя. TODO: проверить правовое основание, сроки хранения и меры защиты с юристом."], ["Передача и отзыв", "Мы не продаём данные. TODO: уточнить возможных обработчиков и порядок отзыва согласия."], ["Аналитика", "На текущем этапе сайт не использует рекламные трекеры и аналитические сервисы."]] : [["Data controller", "Kseniya Galimullina. TODO: verify the controller status and legal details before publication."], ["Data we collect", "Form data: name, contact details, organisation, request type, city and message."], ["Why we use it", "To reply to enquiries, discuss partnership and improve the service."], ["Consent and security", "Data is processed with the visitor’s consent. TODO: verify legal basis, retention and safeguards with counsel."], ["Sharing and withdrawal", "We do not sell data. TODO: specify processors and the withdrawal process."], ["Analytics", "At this stage, the website uses no advertising trackers or analytics services."]]; return <><Header /><main className="legal"><h1>{ru ? "Политика конфиденциальности" : "Privacy policy"}</h1>{blocks.map(([title, text]) => <section key={title}><h2>{title}</h2><p>{text}</p></section>)}</main><Footer /><FloatingContact /></>; }
